#!/usr/bin/env python3
"""Assemble the daily newsletter from pipeline artifacts.

Order: signals first (rules govern), then the Thesis Sentinel brief, then
the PM synthesis, then attribution status. Output: data/newsletter.md
(email body) + frontend/public/data/newsletter.md. The workflow's mail
step sends it if SMTP secrets are configured; otherwise it just lives in
the repo/site.
"""

import json
from datetime import datetime, timezone
from pathlib import Path


def read(path):
    p = Path(path)
    return p.read_text(encoding="utf-8") if p.exists() else ""


def strip_frontmatter(text):
    if text.startswith("---"):
        parts = text.split("---", 2)
        if len(parts) == 3:
            return parts[2].strip()
    return text.strip()


def signals_block():
    raw = read("data/family_signals.json")
    if not raw:
        return "_No signal data._"
    s = json.loads(raw)
    sig = s.get("signals", {})
    lines = [
        f"**Mandate instruction:** {s.get('mandates', {}).get('P_sleeve', '?')}",
        "",
        "| Signal | State | Detail |",
        "|---|---|---|",
    ]
    slow = sig.get("slow_channel", {})
    lines.append(f"| Trend (monthly 200dma) | {slow.get('state','?')} | "
                 f"{slow.get('distance_pct','?')}% vs SMA, as of {slow.get('as_of_month_end','?')} |")
    fast = sig.get("fast_channel", {})
    lines.append(f"| VIX term structure | {fast.get('state','?')} | "
                 f"ratio {fast.get('vix_vix3m_5d_median','?')} |")
    credit = sig.get("credit", {})
    lines.append(f"| Credit (HYG/LQD 63d) | {credit.get('state','?')} | "
                 f"{credit.get('hyg_lqd_63d_relmom','?')} |")
    canary = sig.get("canary", {})
    lines.append(f"| Canary breadth | {canary.get('state','?')} | "
                 f"negative: {canary.get('negative_canaries', [])} |")
    return "\n".join(lines)


def attribution_block():
    raw = read("data/attribution.json")
    if not raw:
        return "_Attribution pending first workflow run._"
    a = json.loads(raw)
    lines = ["| Account | Status |", "|---|---|"]
    for acct, data in a.get("accounts", {}).items():
        status = (data.get("vs_expectation", {}).get("status", "n/a")
                  if data.get("ok") else f"error: {data.get('error','?')[:40]}")
        lines.append(f"| {acct} | {status} |")
    return "\n".join(lines)


def main():
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    sentinel = strip_frontmatter(
        read("frontend/src/content/reports/thesis_sentinel.md"))
    synthesis = strip_frontmatter(
        read("frontend/src/content/reports/pm_synthesis.md"))

    newsletter = f"""# AlphaOracle Daily - {today}

## Signals (rules govern; everything below is commentary)

{signals_block()}

## Thesis Sentinel

{sentinel or '_No sentinel brief this run._'}

## Portfolio Manager Synthesis

{synthesis or '_No synthesis this run._'}

## Paper-Account Attribution

{attribution_block()}

---
Generated by AlphaOracle. Paper trading only; research, not advice.
Dashboard: https://srajabi.github.io/AlphaOracle/
"""
    for base in [Path("data"), Path("frontend/public/data")]:
        base.mkdir(parents=True, exist_ok=True)
        (base / "newsletter.md").write_text(newsletter, encoding="utf-8")
    print(f"newsletter.md written ({len(newsletter)} chars)")


if __name__ == "__main__":
    main()
