import os
import json
import litellm
from datetime import datetime
from dotenv import load_dotenv

# Load local .env automatically for development.
load_dotenv()


def parse_models(models_env_var, model_env_var, default_model):
    """
    Prefer comma-separated *_MODELS, fall back to single *_MODEL,
    then to a sensible default.
    """
    multi = os.getenv(models_env_var, "").strip()
    if multi:
        return [m.strip() for m in multi.split(",") if m.strip()]

    single = os.getenv(model_env_var, "").strip()
    if single:
        return [single]

    return [default_model]


DEFAULT_ROLE_MODEL = os.getenv("DEFAULT_ROLE_MODEL", "deepseek/deepseek-reasoner")
DEFAULT_PM_MODEL = os.getenv("DEFAULT_PM_MODEL", "deepseek/deepseek-reasoner")

RISK_MODELS = parse_models("RISK_MODELS", "RISK_MODEL", DEFAULT_ROLE_MODEL)
TECH_MODELS = parse_models("TECH_MODELS", "TECH_MODEL", DEFAULT_ROLE_MODEL)
MACRO_MODELS = parse_models("MACRO_MODELS", "MACRO_MODEL", DEFAULT_ROLE_MODEL)
PM_MODEL = os.getenv("PM_MODEL", DEFAULT_PM_MODEL)

def load_text_file(filepath):
    if os.path.exists(filepath):
        with open(filepath, 'r') as f:
            return f.read()
    return ""

def build_context():
    # Load Market Data
    market_data_str = load_text_file('data/market_context.json')
    options_data_str = load_text_file('data/options_context.json')
    
    # Load Thesis
    macro_view = load_text_file('thesis/macro_view.md')
    sectors = load_text_file('thesis/sectors.md')
    seasonality = load_text_file('thesis/seasonality_rules.md')
    
    # Load Portfolio & Watchlist
    portfolio = load_text_file('portfolio.csv')
    watchlist = load_text_file('watchlist.csv')

    context = f"""
# MARKET DATA (JSON)
{market_data_str}

# OPTIONS IDEAS AND CHAIN SNAPSHOT (JSON)
{options_data_str}

# CURRENT PORTFOLIO STATE
{portfolio}

# WATCHLIST
{watchlist}

# INVESTMENT THESIS
## Macro View
{macro_view}

## Sectors
{sectors}

## Seasonality Rules
{seasonality}
"""
    return context

def run_agent(role, prompt, model, context):
    print(f"Running {role} agent with model {model}...")
    
    if os.getenv("MOCK_LLM") == "true":
        print(f"MOCK_LLM is true. Using mocked completion for {role}.")
        # Provide a simple mocked response structure
        mock_content = f"Mocked {role} report: Market looks stable for {role}. No strong signals. AI is the future. {model} was used."
        return mock_content

    try:
        response = litellm.completion(
            model=model,
            messages=[
                {"role": "system", "content": f"You are an expert {role} in a quantitative hedge fund."},
                {"role": "user", "content": f"Here is the context:\n{context}\n\nTask: {prompt}"}
            ]
        )
        return response.choices[0].message.content
    except Exception as e:
        print(f"Error running {role} with {model}: {e}")
        return f"Error: {e}"


def run_role_agents(role, prompt, models, context):
    reports = []
    for model in models:
        content = run_agent(role, prompt, model, context)
        reports.append({"model": model, "content": content})
    return reports


def format_role_report_for_site(role_reports):
    sections = []
    for report in role_reports:
        sections.append(f"## Model: {report['model']}\n\n{report['content']}")
    return "\n\n---\n\n".join(sections)


def format_role_report_for_pm(role_name, role_reports):
    blocks = []
    for idx, report in enumerate(role_reports, start=1):
        blocks.append(
            f"### {role_name} Report {idx} (Generated by: {report['model']})\n{report['content']}"
        )
    return "\n\n".join(blocks)

def generate_reports():
    context = build_context()
    date_str = datetime.now().strftime("%Y-%m-%d")
    print(
        "Model selection:",
        f"risk={RISK_MODELS}, tech={TECH_MODELS}, macro={MACRO_MODELS}, pm={PM_MODEL}"
    )
    
    # 1. Risk Manager
    risk_prompt = (
        "Focus entirely on downside protection and geopolitical risk. Analyze the market regime, volatility (VIX), "
        "ticker-level weakness, and especially the structured `macro_news` and `theme_news` in the "
        "market context JSON.\n\n"
        "**CRITICAL: Look for these specific geopolitical catalysts:**\n"
        "- Strait of Hormuz / Middle East tensions (Iran-Israel, oil shipping disruption)\n"
        "- China-Taiwan escalation (semiconductor supply chain risk)\n"
        "- Trade war / sanctions / export controls\n"
        "- Fed policy surprises (hawkish/dovish pivot)\n"
        "- Recession signals (layoffs, unemployment, economic slowdown)\n\n"
        "For any geopolitical event, specify:\n"
        "1. What happened and severity (1-10)\n"
        "2. Which sectors/tickers are most exposed (bullish/bearish)\n"
        "3. Recommended hedges (protective puts, safe havens, sector rotation)\n"
        "4. Time horizon (immediate, days, weeks)\n\n"
        "Explain what should be sold, trimmed, hedged, or avoided."
    )
    risk_reports = run_role_agents("Risk Manager", risk_prompt, RISK_MODELS, context)
    
    # 2. Technical Analyst
    tech_prompt = (
        "Ignore the news and focus on price action only. Evaluate the setups purely based on "
        "price, moving averages (SMA_20, SMA_50, SMA_200), RSI, MACD, and Bollinger Bands. "
        "Identify mean reversion bounces, trend continuation, failed setups, or volatility "
        "contraction squeezes."
    )
    tech_reports = run_role_agents("Technical Analyst", tech_prompt, TECH_MODELS, context)
    
    # 3. Macro Strategist
    macro_prompt = (
        "Focus on the macro view, geopolitical events, and global market regime. Review the structured "
        "`macro_news` and `theme_news` in the market context JSON carefully.\n\n"
        "**Key areas to analyze:**\n"
        "1. **Geopolitical Events**: Strait of Hormuz tensions, China-Taiwan, Middle East conflicts\n"
        "   - Map events to sectors: Energy (XLE), Safe havens (GLD, TLT), Defensives (XLU, XLP)\n"
        "   - Identify risk-on vs risk-off positioning\n\n"
        "2. **Fed Policy & Rates**: Any hawkish/dovish signals, CPI surprises, yield curve changes\n"
        "   - Duration trade: TLT behavior\n"
        "   - Growth vs Value rotation signals\n\n"
        "3. **Cross-Asset Signals**: Dollar strength, commodities, credit spreads\n"
        "   - Flight to safety indicators\n"
        "   - Stagflation vs reflationary signals\n\n"
        "4. **Sector Rotation**: Which sectors are showing leadership changes?\n"
        "   - Energy, Tech, Defensives, Financials, International\n\n"
        "Be explicit about second-order effects. For example:\n"
        "- Hormuz tensions → Oil up → XLE bullish, airlines bearish, inflation concerns → TLT demand\n"
        "- Taiwan tensions → TSM risk → INTC opportunity, tech supply chain disruption\n\n"
        "Determine whether events imply regime change, sector rotation, or positioning adjustments."
    )
    macro_reports = run_role_agents("Macro Strategist", macro_prompt, MACRO_MODELS, context)

    risk_report_site = format_role_report_for_site(risk_reports)
    tech_report_site = format_role_report_for_site(tech_reports)
    macro_report_site = format_role_report_for_site(macro_reports)
    
    # 4. Portfolio Manager (Synthesizer)
    pm_prompt = f"""
You are the Lead Portfolio Manager. Review the reports from your analysts below. 
Note: The source model used to generate each report is provided. When debating disagreements, you should generally heavily weight opinions from advanced/paid frontier models (e.g., GPT-4, Claude 3.5 Sonnet) over faster/free-tier models (e.g., Gemini Flash, Llama 3 8B), while still considering the merit of the underlying argument.

## Risk Manager Inputs
{format_role_report_for_pm("Risk Manager", risk_reports)}

## Technical Analyst Inputs
{format_role_report_for_pm("Technical Analyst", tech_reports)}

## Macro Strategist Inputs
{format_role_report_for_pm("Macro Strategist", macro_reports)}

Weigh these inputs against our investment thesis and portfolio constraints.
Explicitly incorporate the structured macro and theme news from the market context, especially when
recent geopolitical, commodity, inflation, shipping, sanctions, or policy events could materially
change positioning.
Use the options context only for idea generation and hedging suggestions. Do not emit options trades
in the final executable JSON array because the execution layer is currently equity-only.
Debate disagreements. Output a definitive, actionable plan.

FIRST, provide your analysis and a strict Markdown table containing:
| Action (Buy/Sell/Hold) | Ticker/Asset | Conviction Level (High/Medium/Low) | Timeframe | Justification |

SECOND, at the very end of your response, output a strict, parseable JSON array of the trades you want to execute. Do not include 'Hold' actions in the JSON. For fractionable shares, use dollar amounts instead of shares. Wrap the JSON in a markdown code block like ```json ... ```.

The JSON format MUST be exactly this structure:
[
  {{
    "ticker": "MSFT",
    "action": "buy",
    "notional_value": 200000
  }},
  {{
    "ticker": "AAPL",
    "action": "sell",
    "qty": "all"
  }}
]
"""
    pm_report = run_agent("Portfolio Manager", pm_prompt, PM_MODEL, context)
    
    # Extract JSON trades
    trades = []
    display_report = pm_report
    try:
        # Simple extraction looking for ```json ... ```
        if "```json" in pm_report:
            json_str = pm_report.split("```json")[1].split("```")[0].strip()
            trades = json.loads(json_str)
            # Remove the JSON block from the display report so the website looks clean
            display_report = pm_report.split("```json")[0].strip()
    except Exception as e:
        print(f"Failed to extract JSON trades from PM report: {e}")

    with open('data/trades.json', 'w') as f:
        json.dump(trades, f, indent=4)
        print("Trades saved to data/trades.json")

    
    # Save reports
    reports_dir = 'frontend/src/content/reports'
    os.makedirs(reports_dir, exist_ok=True)
    
    with open(f'{reports_dir}/risk.md', 'w') as f:
        f.write(f"---\ntitle: Risk Manager Report\ndate: \"{date_str}\"\n---\n\n{risk_report_site}")
        
    with open(f'{reports_dir}/tech.md', 'w') as f:
        f.write(f"---\ntitle: Technical Analyst Report\ndate: \"{date_str}\"\n---\n\n{tech_report_site}")
        
    with open(f'{reports_dir}/macro.md', 'w') as f:
        f.write(f"---\ntitle: Macro Strategist Report\ndate: \"{date_str}\"\n---\n\n{macro_report_site}")
        
    with open(f'{reports_dir}/pm_synthesis.md', 'w') as f:
        f.write(f"---\ntitle: AlphaOracle Daily Synthesis\ndate: \"{date_str}\"\n---\n\n{display_report}")
        
    print("Reports generated successfully.")

if __name__ == "__main__":
    generate_reports()
